### ISSUE TITLE
Invitación para integración de Dataset a nivel latinoamérica

### ISSUE THREAD

**Issue by ZurMaD** [erianvc/COVID-Peru#2]
Hola, junto con una organización sin fines de lucro se está tratando de centralizar la información de contagiados/muertos/recuperados covid-19 y estamos buscando un encargado por país. En este caso sería el de Perú.

El formato de los archivos es el de número de contagiados/muertos/recuperados por departamento por día:

![image](https://user-images.githubusercontent.com/28235457/77831081-ee473380-70fa-11ea-9feb-43fcc0a4f703.png)

Dentro de cada archivo (.csv) respectivo al caso total hasta ese día se tiene que rellenar las siguientes filas:
Por ejemplo para el día [2020-03-28](https://github.com/DataScienceResearchPeru/covid-19_latinoamerica/blob/master/latam_covid_19_data/latam_covid_19_daily_reports/2020-03-28.csv)

![image](https://user-images.githubusercontent.com/28235457/77831117-20589580-70fb-11ea-9e6c-209d434d48a9.png)

Podrías comentarme si estás interesado en aportar porfavor.
El dataset centralizado se propone en este repositorio: https://github.com/DataScienceResearchPeru/covid-19_latinoamerica
Se te puede dar acceso nivel `Maintainer` al repositorio mencionado, ya hay encargados de varios países.

**Comment by erianvc** [comment]
Claro, me gustaría colaborar

**Comment by ZurMaD** [comment]
Hola te agrego al repositorio con nivel Maintainer porfa revisa el repo y como son el formato de los commits, tenemos un slack y un mapa.
